### ISSUE TITLE
Documentation subdomain produces "too many redirects" error

### ISSUE THREAD

**Issue by felciano** [gaborschulz/synctodoist#53]
When trying to go to your documentation website https://synctodoist.gaborschulz.com, browsers fail with a "too many redirects" error. Tested on Chrome and Safari, including with incognito mode. 

https://gaborschulz.com redirects correctly to LI, so looks like this a problem with the `synctodoist` subdomain only.

**Comment by gaborschulz** [comment]
Thanks for calling it out. The url should be working again.
